NANOSECS = 1
MICROSECS = 1000 * NANOSECS
MILLISECS = 1000 * MICROSECS
SECS = 1000 * MILLISECS

MINE_RATE = 4 * SECS

WALLET_STARTING_BALANCE = 1000

THE_MINING_REWARD = 50
INPUT_FOR_MINING_REWARD = {'address': '♛⊶The-Official-The-Mining-Reward⊷♛'}